name: Deno Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [development, master, main, automation/deno-yaml]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Deno tests and collect coverage
        run: |
          mkdir -p cov
          deno test test/ --coverage=cov --allow-read=test --allow-env || echo "No tests found, skipping..."

      - name: Generate lcov report
        run: |
          if deno coverage cov --lcov --exclude=test > coverage.lcov; then
            echo "Coverage report generated."
          else
            echo "No covered files found, skipping coverage report."
            touch coverage.lcov  # create empty file to upload
          fi

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: deno-coverage
          path: coverage.lcov
          retention-days: 30
